//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falplayer
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int PlayButton = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int RescanButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int SelectButton = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int SongSeekbar = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int SongTitleTextView = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int StopButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int TimelineTextView = 2131034117;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FileGroupSelectorListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
